# ===============================
#   (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://uabvnk4dy2zyxcfx:ZSzjWsbaHeO6pxfwxgcw@bzf3fjp0wy4z8b0owgrg-mysql.services.clever-cloud.com:3306/bzf3fjp0wy4z8b0owgrg
spring.datasource.username=root
spring.datasource.password=qwerty12345@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
#JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ===============================

# ===============================
server.port=8085
spring.main.web-application-type=servlet

# ===============================

# ===============================
currency.mode=api
