# ===============================
#    (MySQL - Clever Cloud)
# ===============================

spring.datasource.url=jdbc:mysql://bzf3fjp0wy4z8b0owgrg-mysql.services.clever-cloud.com:3306/bzf3fjp0wy4z8b0owgrg
spring.datasource.username=uabvnk4dy2zyxcfx
spring.datasource.password=ZSzjWsbaHeO6pxfwxgcw
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

# ===============================
#   JPA / Hibernate
# ===============================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===============================
# ===============================
server.port=8085
spring.main.web-application-type=servlet

currency.mode=api
