# ===============================
#    (MySQL - Clever Cloud)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=20000
spring.datasource.hikari.initialization-fail-timeout=0

# ===============================
#   JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.jpa.defer-datasource-initialization=true

# ===============================
# ===============================
server.port=8087
spring.main.web-application-type=servlet

currency.mode=api

# ===============================
#   Trello API
# ===============================
trello.api.endpoint.prod=https://api.trello.com/1
trello.app.key=${TRELLO_API_KEY}
trello.app.token=${TRELLO_API_TOKEN}
trello.app.username=${TRELLO_USERNAME}
