USE kodilla_course;

CREATE TABLE BOOKS_AUD (
   EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
   EVENT_DATE DATETIME NOT NULL,
   EVENT_TYPE VARCHAR(10) DEFAULT NULL,
   BOOK_ID INT(11) NOT NULL,
   OLD_TITLE VARCHAR(255),
   NEW_TITLE VARCHAR(255),
   OLD_AUTHOR VARCHAR(255),
   NEW_AUTHOR VARCHAR(255),
   OLD_PUBLISHED_YEAR INT(11),
   NEW_PUBLISHED_YEAR INT(11),
   OLD_BESTSELLER BOOLEAN,
   NEW_BESTSELLER BOOLEAN,
   PRIMARY KEY (EVENT_ID)
);

CREATE TABLE READERS_AUD (
   EVENT_ID INT(11) NOT NULL AUTO_INCREMENT,
   EVENT_DATE DATETIME NOT NULL,
   EVENT_TYPE VARCHAR(10) DEFAULT NULL,
   READER_ID INT(11) NOT NULL,
   OLD_USER_ID INT(11),
   NEW_USER_ID INT(11),
   OLD_LIBRARY_CARD_NUMBER VARCHAR(50),
   NEW_LIBRARY_CARD_NUMBER VARCHAR(50),
   PRIMARY KEY (EVENT_ID)
);

DELIMITER $$

CREATE TRIGGER BOOKS_INSERT AFTER INSERT ON BOOKS
FOR EACH ROW
BEGIN
   INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_AUTHOR,
                          NEW_PUBLISHED_YEAR, NEW_BESTSELLER)
      VALUE(CURTIME(), "INSERT", NEW.book_id, NEW.title, NEW.author,
            NEW.published_year, NEW.bestseller);
END $$

CREATE TRIGGER BOOKS_DELETE AFTER DELETE ON BOOKS
FOR EACH ROW
BEGIN
   INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, OLD_TITLE, OLD_AUTHOR,
                          OLD_PUBLISHED_YEAR, OLD_BESTSELLER)
      VALUE(CURTIME(), "DELETE", OLD.book_id, OLD.title, OLD.author,
            OLD.published_year, OLD.bestseller);
END $$

CREATE TRIGGER BOOKS_UPDATE AFTER UPDATE ON BOOKS
FOR EACH ROW
BEGIN
   INSERT INTO BOOKS_AUD (EVENT_DATE, EVENT_TYPE, BOOK_ID, NEW_TITLE, NEW_AUTHOR,
                          NEW_PUBLISHED_YEAR, NEW_BESTSELLER, OLD_TITLE, OLD_AUTHOR,
                          OLD_PUBLISHED_YEAR, OLD_BESTSELLER)
      VALUE(CURTIME(), "UPDATE", OLD.book_id, NEW.title, NEW.author,
            NEW.published_year, NEW.bestseller, OLD.title, OLD.author,
            OLD.published_year, OLD.bestseller);
END $$

DELIMITER ;

DELIMITER $$

CREATE TRIGGER READERS_INSERT AFTER INSERT ON READERS
FOR EACH ROW
BEGIN
   INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_USER_ID,
                            NEW_LIBRARY_CARD_NUMBER)
      VALUE(CURTIME(), "INSERT", NEW.reader_id, NEW.user_id, NEW.library_card_number);
END $$

CREATE TRIGGER READERS_DELETE AFTER DELETE ON READERS
FOR EACH ROW
BEGIN
   INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, OLD_USER_ID,
                            OLD_LIBRARY_CARD_NUMBER)
      VALUE(CURTIME(), "DELETE", OLD.reader_id, OLD.user_id, OLD.library_card_number);
END $$

CREATE TRIGGER READERS_UPDATE AFTER UPDATE ON READERS
FOR EACH ROW
BEGIN
   INSERT INTO READERS_AUD (EVENT_DATE, EVENT_TYPE, READER_ID, NEW_USER_ID,
                            NEW_LIBRARY_CARD_NUMBER, OLD_USER_ID, OLD_LIBRARY_CARD_NUMBER)
      VALUE(CURTIME(), "UPDATE", OLD.reader_id, NEW.user_id, NEW.library_card_number,
            OLD.user_id, OLD.library_card_number);
END $$

DELIMITER ;
