USE kodilla_course;

CREATE TABLE STATS (
   STAT_ID INT(11) NOT NULL AUTO_INCREMENT,
   STAT_DATE DATETIME NOT NULL,
   STAT VARCHAR(20) NOT NULL,
   VALUE INT(11) NOT NULL,
   PRIMARY KEY (STAT_ID)
);

CREATE VIEW BESTSELLERS_COUNT AS
SELECT COUNT(*) AS COUNT FROM BOOKS WHERE BESTSELLER = 1;

SET GLOBAL EVENT_SCHEDULER = ON;

DROP EVENT IF EXISTS UPDATE_BESTSELLERS_STATS;

DELIMITER $$

CREATE EVENT UPDATE_BESTSELLERS_STATS
   ON SCHEDULE EVERY 1 MINUTE
   DO BEGIN
      CALL UpdateBestsellers();

      INSERT INTO STATS (STAT_DATE, STAT, VALUE)
         SELECT NOW(), 'BESTSELLERS', COUNT FROM BESTSELLERS_COUNT;
   END $$

DELIMITER ;
